config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  resources :cards, only: %i[ index show ]
  resources :card_sets, only: %i[ index show ]

  get "about" => "about#about", as: "about"
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attack.rb
class Attack < ApplicationRecord
  has_many :card_attacks, dependent: :destroy
  has_many :cards, through: :card_attacks
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :card_set
  belongs_to :supertype
  belongs_to :rarity
  belongs_to :pokemon_type, optional: true
  belongs_to :image_url, class_name: "Image"

  has_many :card_attacks
  has_many :attacks, through: :card_attacks
  validates :name, :card_number, :supertype, :rarity, :card_set, :image_url, presence: true
end

app/models/card_attack.rb
class CardAttack < ApplicationRecord
  belongs_to :attack
  belongs_to :card
end

app/models/card_set.rb
class CardSet < ApplicationRecord
  has_many :cards, foreign_key: "card_set_id", dependent: :destroy
  belongs_to :logo, class_name: "Image"
  validates :name, :series, :release_date, :logo, presence: true
end

app/models/image.rb
class Image < ApplicationRecord
  has_many :cards, foreign_key: "image_url_id", dependent: :nullify
  has_many :card_sets, foreign_key: "logo_id", dependent: :nullify
  validates :image_url, presence: true
end

app/models/pokemon_type.rb
class PokemonType < ApplicationRecord
  has_many :cards
  validates :name, presence: true
end

app/models/rarity.rb
class Rarity < ApplicationRecord
  has_many :cards
  validates :name, presence: true
end

app/models/set.rb
class Set < ApplicationRecord
  has_many :cards
  belongs_to :logo, class_name: "Image"
  validates :name, :release_date, :logo, presence: true
end

app/models/supertype.rb
class Supertype < ApplicationRecord
  has_many :cards
  validates :name, presence: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @cards = Card.includes(:card_set, :image_url).order("RANDOM()").limit(12)
    @card_sets = CardSet.order("RANDOM()").limit(12)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attacks_helper.rb
module AttacksHelper
end

app/helpers/card_types_helper.rb
module CardTypesHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/rarities_helper.rb
module RaritiesHelper
end

app/helpers/sets_helper.rb
module SetsHelper
end

app/helpers/supertypes_helper.rb
module SupertypesHelper
end

app/views/common/_footer.html.erb
<footer class="footer footer-background-color py-5">
  <div class="container has-text-centered">
    <ul class="is-inline-flex is-justify-content-center is-align-items-center mb-3" style="list-style: none; padding: 0; gap: 1.5rem;">
      <% unless controller_name == "home" %>
        <li><%= link_to "Home", root_path, class: "navbar-link" %></li>
      <% end %>
      <li><%= link_to "Sets", card_sets_path, class: "navbar-link" %></li>
      <li><%= link_to "Cards", cards_path, class: "navbar-link" %></li>
      <li><%= link_to "About", about_path, class: "navbar-link" %></li>
    </ul>

    <p class="has-text-grey">Oppositewrong © 2025</p>
  </div>
</footer>

app/views/common/_navigation.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-menu is-active is-flex is-justify-content-center">
    <ul class="navbar-item" style="display: flex; gap: 1.5rem; list-style: none;">
      <% unless controller_name == "home" %>
        <li><%= link_to "Home", root_path, class: "navbar-link" %></li>
      <% end %>
      <li><%= link_to "Sets", card_sets_path, class: "navbar-link" %></li>
      <li><%= link_to "Cards", cards_path, class: "navbar-link" %></li>
      <li><%= link_to "About", about_path, class: "navbar-link" %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= content_for(:title) || "Intro Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma@1.0.4/css/bulma.min.css"
    >
  </head>

  <body>
    <%= render "common/navigation"%>
    <%= yield %>
    <%= render "common/footer" %>
  </body>
</html>